apiVersion: v1
kind: Service
metadata:
  name: thai-menu-frontend-service
spec:
  type: NodePort
  selector:
    app: thai-menu-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
